name: Dependency Updates

on:
  pull_request:
    paths:
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

jobs:
  test-dependency-updates:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests with updated dependencies
      run: npm test
      
    - name: Build with updated dependencies
      run: npm run build
      
    - name: Security audit
      run: npm audit
      
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    needs: test-dependency-updates
    
    steps:
    - name: Enable auto-merge for Dependabot PRs
      if: success()
      run: |
        gh pr merge --auto --squash "$PR_URL"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_URL: ${{ github.event.pull_request.html_url }}
